version: '2'
services:
  fusion-release-test:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
    volumes:
      - '.:/fusion-release-test'
      - /fusion-release-test/node_modules/
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent
