steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-release-test
        config: docker-compose.test.yml
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-release-test
        config: docker-compose.test.yml
    agents:
      queue: workers
